Build: so_stdio.lib

so_stdio.lib: so_stdio.obj 
	cl /LD so_stdio.obj
	link /nologo /dll /out:so_stdio.dll /implib:so_stdio.lib so_stdio.obj

so_stdio.obj: so_stdio.c so_stdio.h
	cl /c so_stdio.c